"""Run the Section 5.4 lateness-sensitivity experiment.

The experiment uses the J=4 instance, common-random-number design, specified
lateness multipliers, seeds, and scenario counts.  Schedules are generated by
DE-MILP and evaluated by the independent fixed-schedule validator.
"""

from __future__ import annotations

import argparse
import csv
import gc
import math
import os
from typing import Dict, Iterable, List, Tuple

import numpy as np

from scenario_generation import generate_all_scenarios
from model_utils import compute_data_driven_bigM
from fixed_schedule_validation import validate_fixed_schedule
from run_section53_exact import solve_de_milp


FIELDS = [
    "protocol_version",
    "J",
    "K",
    "kappa",
    "rep",
    "seed_service",
    "seed_lateness",
    "tau_mean",
    "psi_mean",
    "status",
    "certified",
    "solver_obj",
    "validated_obj",
    "alpha_sum",
    "beta_sum",
    "validation_status",
    "validation_max_violation",
    "runtime_sec",
    "build_sec",
    "solve_sec",
    "solver_bound",
    "relative_gap",
]


def generate_base_scenarios(
    count: int,
    c: np.ndarray,
    seed_service: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    return generate_all_scenarios(
        numSamples=count,
        numStages=3,
        numPositions=4,
        numPatients=4,
        c=c,
        seed=seed_service,
    )


def append_row(path: str, row: Dict) -> None:
    new_file = not os.path.exists(path) or os.path.getsize(path) == 0
    with open(path, "a", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        if new_file:
            writer.writeheader()
        writer.writerow({field: row.get(field, "") for field in FIELDS})
        handle.flush()


def existing_keys(path: str) -> set[Tuple[int, int, float]]:
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return set()
    with open(path, "r", newline="", encoding="utf-8-sig") as handle:
        return {
            (int(row["rep"]), int(row["K"]), float(row["kappa"]))
            for row in csv.DictReader(handle)
        }


def finite(values: Iterable[float]) -> np.ndarray:
    data = np.asarray([float(value) for value in values], dtype=float)
    return data[np.isfinite(data)]


def build_summary(raw_path: str, summary_path: str) -> None:
    with open(raw_path, "r", newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.DictReader(handle))
    grouped: Dict[Tuple[int, float], List[Dict]] = {}
    for row in rows:
        grouped.setdefault((int(row["K"]), float(row["kappa"])), []).append(row)
    fields = [
        "K",
        "kappa",
        "n",
        "obj_mean",
        "obj_std",
        "alpha_mean",
        "alpha_std",
        "beta_mean",
        "beta_std",
        "tau_mean",
        "tau_std",
        "psi_mean",
        "psi_std",
        "runtime_mean",
        "runtime_std",
        "certified_runs",
        "validation_pass_runs",
    ]
    with open(summary_path, "w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for (K, kappa), group in sorted(grouped.items()):
            objective = finite(row["validated_obj"] for row in group)
            alpha = finite(row["alpha_sum"] for row in group)
            beta = finite(row["beta_sum"] for row in group)
            tau = finite(row["tau_mean"] for row in group)
            psi = finite(row["psi_mean"] for row in group)
            runtime = finite(row["runtime_sec"] for row in group)

            def avg(values: np.ndarray) -> float:
                return float(np.mean(values)) if values.size else math.nan

            def std(values: np.ndarray) -> float:
                return float(np.std(values, ddof=1)) if values.size > 1 else 0.0

            writer.writerow(
                {
                    "K": K,
                    "kappa": kappa,
                    "n": int(objective.size),
                    "obj_mean": avg(objective),
                    "obj_std": std(objective),
                    "alpha_mean": avg(alpha),
                    "alpha_std": std(alpha),
                    "beta_mean": avg(beta),
                    "beta_std": std(beta),
                    "tau_mean": avg(tau),
                    "tau_std": std(tau),
                    "psi_mean": avg(psi),
                    "psi_std": std(psi),
                    "runtime_mean": avg(runtime),
                    "runtime_std": std(runtime),
                    "certified_runs": sum(int(row["certified"]) for row in group),
                    "validation_pass_runs": sum(
                        row["validation_status"] == "PASS" for row in group
                    ),
                }
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reps", type=int, default=10)
    parser.add_argument("--seed-base", type=int, default=2025)
    parser.add_argument("--seed-stride", type=int, default=10)
    parser.add_argument("--K", default="50,200,500")
    parser.add_argument("--kappa", default="0,0.25,0.75,1,1.5,2")
    parser.add_argument("--budget", type=float, default=120.0)
    parser.add_argument("--mip-gap", type=float, default=1e-4)
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--output-flag", type=int, default=0)
    parser.add_argument("--output", default="section54_results_long.csv")
    parser.add_argument("--summary", default="section54_summary.csv")
    args = parser.parse_args()

    K_values = [int(item) for item in args.K.split(",") if item.strip()]
    kappas = [float(item) for item in args.kappa.split(",") if item.strip()]
    max_K = max(K_values)
    c = np.asarray(
        [
            [0, 0, 1, 1],
            [0, 0, 1, 1],
            [1, 1, 0, 0],
        ],
        dtype=int,
    )
    r_d = np.asarray([2.0, 2.0, 2.4, 2.4], dtype=float)
    r_s = np.asarray([3.2, 3.2, 4.0, 4.0], dtype=float)
    limits = np.asarray([2.0, 5.0, 2.0], dtype=float)
    iv = [int(np.sum(c[h, :] == 0)) for h in range(3)]
    done = existing_keys(args.output)

    for rep in range(args.reps):
        seed_service = int(args.seed_base + args.seed_stride * rep)
        seed_lateness = seed_service
        s_all, tau_all, psi_all = generate_base_scenarios(
            max_K, c, seed_service
        )
        for K in K_values:
            s = np.asarray(s_all[:K], dtype=float)
            tau_base = np.asarray(tau_all[:K], dtype=float)
            psi_base = np.asarray(psi_all[:K], dtype=float)
            p = np.full(K, 1.0 / K, dtype=float)
            for kappa in kappas:
                key = (rep, K, kappa)
                if key in done:
                    continue
                tau = np.clip(kappa * tau_base, 0.0, 0.5)
                psi = np.clip(kappa * psi_base, 0.0, 0.5)
                big_m = compute_data_driven_bigM(
                    s=s,
                    tau=tau,
                    psi=psi,
                    c=c,
                    L=limits,
                    Iv=iv,
                )
                inst = {
                    "H": 3,
                    "I": 4,
                    "J": 4,
                    "K": K,
                    "c": c,
                    "r_d": r_d,
                    "r_s": r_s,
                    "L": limits,
                    "Iv": iv,
                    "s": s,
                    "tau": tau,
                    "psi": psi,
                    "p": p,
                    "bigM": big_m,
                    "seed_service": seed_service,
                    "seed_lateness": seed_lateness,
                }
                result = solve_de_milp(
                    inst,
                    budget=args.budget,
                    mip_gap=args.mip_gap,
                    threads=args.threads,
                    output_flag=args.output_flag,
                    progress_checkpoints=(),
                )
                validation_status = "NO_SCHEDULE"
                validated_obj = math.nan
                alpha_sum = math.nan
                beta_sum = math.nan
                max_violation = math.inf
                if result.x is not None and result.y is not None:
                    validation = validate_fixed_schedule(inst, result.x, result.y)
                    validation_status = validation.status
                    max_violation = validation.max_violation
                    if validation.feasible:
                        validated_obj = validation.objective
                        alpha_sum = float(np.sum(validation.alpha))
                        beta_sum = float(np.sum(validation.beta))
                row = {
                    "protocol_version": "EJOR-SECTION54-PROTOCOL",
                    "J": 4,
                    "K": K,
                    "kappa": kappa,
                    "rep": rep,
                    "seed_service": seed_service,
                    "seed_lateness": seed_lateness,
                    "tau_mean": float(np.mean(tau)),
                    "psi_mean": float(np.mean(psi)),
                    "status": result.status,
                    "certified": int(result.certified),
                    "solver_obj": result.obj,
                    "validated_obj": validated_obj,
                    "alpha_sum": alpha_sum,
                    "beta_sum": beta_sum,
                    "validation_status": validation_status,
                    "validation_max_violation": max_violation,
                    "runtime_sec": result.runtime_sec,
                    "build_sec": result.build_sec,
                    "solve_sec": result.solve_sec,
                    "solver_bound": result.bound,
                    "relative_gap": result.rel_gap,
                }
                append_row(args.output, row)
                done.add(key)
                build_summary(args.output, args.summary)
                print(
                    f"rep={rep} K={K} kappa={kappa:g}: "
                    f"status={validation_status} obj={validated_obj:.6g} "
                    f"certified={int(result.certified)} time={result.runtime_sec:.2f}s",
                    flush=True,
                )
                del result
                gc.collect()
        del s_all, tau_all, psi_all
        gc.collect()
    build_summary(args.output, args.summary)


if __name__ == "__main__":
    main()
